apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mafia-backend
  template:
    metadata:
      labels:
        app: mafia-backend
    spec:
      containers:
      - name: mafia-backend
        image: {{ .Values.backendImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
