apiVersion: apps/v1
kind: Deployment
metadata:
  name: mafia-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mafia-frontend
  template:
    metadata:
      labels:
        app: mafia-frontend
    spec:
      containers:
      - name: mafia-frontend
        image: {{ .Values.frontendImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
