name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
    
    # Если вы собираете образы в CI:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Сборка и пуш образов (опционально, если вам нужно):
    - name: Build and push backend image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/mafia-backend:latest ./backend
        docker push ghcr.io/${{ github.repository }}/mafia-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/mafia-frontend:latest ./frontend
        docker push ghcr.io/${{ github.repository }}/mafia-frontend:latest
    
    # Настройка доступа к кластеру
    # Вам понадобится kubeconfig или токен доступа.
    # Допустим, вы сохраните kubeconfig в GitHub Secrets.
    # В GitHub репозитории зайдите в Settings > Security > Secrets and variables > Actions
    # и добавьте секрет под именем KUBECONFIG_DATA (base64 кодированное содержимое kubeconfig)
    - name: Set Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
      shell: bash
    
    # Деплой через Helm
    - name: Helm upgrade/install
      run: |
        helm upgrade --install mafia ./mafia-chart --set backendImage=ghcr.io/${{ github.repository }}/mafia-backend:latest --set frontendImage=ghcr.io/${{ github.repository }}/mafia-frontend:latest
